/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-07-30 07:16:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table style=\"width:100%; border: 1px solid black\">\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t        <!-- footer -->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("\t<!--footer 메뉴 -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"f_menu\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"f_mu_left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/info/company.asp\"><img src=\"./img/f_ltt01.gif\" alt=\"회사소개\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img src=\"./img/f_lttline.gif\" alt=\"가운데라인\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"http://giftkor.giftmani.com/board/board06.asp\"><img src=\"./img/f_ltt02.gif\" alt=\"개인정보취급방침\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img src=\"./img/f_lttline.gif\" alt=\"가운데라인\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"http://giftkor.giftmani.com/board/board07.asp\"><img src=\"./img/f_ltt03.gif\" alt=\"이용약관\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img src=\"./img/f_lttline.gif\" alt=\"가운데라인\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"http://giftkor.giftmani.com/board/notice.asp\"><img src=\"./img/f_ltt04.gif\" alt=\"고객지원센터\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img src=\"./img/f_lttline.gif\" alt=\"가운데라인\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"./img/f_ltt05.gif\" alt=\"커뮤니티\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"f_mu_right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img class=\"f_dot\" src=\"./img/f_ttdot.gif\" alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"./img/f_rtt01.gif\" alt=\"상품입점\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img class=\"f_dot\"  src=\"./img/f_ttdot.gif\" alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"./img/f_rtt02.gif\" alt=\"제조업체로그인\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img class=\"f_dot\"  src=\"./img/f_ttdot.gif\" alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"./img/f_rtt03.gif\" alt=\"상품등록방법\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img class=\"f_dot\"  src=\"./img/f_ttdot.gif\" alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"./img/f_rtt04.gif\" alt=\"체인모집안내\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img class=\"f_dot\"  src=\"./img/f_ttdot.gif\" alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\" id=\"morselJumun\"><img src=\"./img/f_rtt05.gif\" alt=\"소량구매\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img class=\"f_dot\"  src=\"./img/f_ttdot.gif\" alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"./img/f_rtt06.gif\" alt=\"특판상품\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img class=\"f_dot\"  src=\"./img/f_ttdot.gif\" alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"./img/f_rtt07.gif\" alt=\"주문서\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--// footer 메뉴 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- footer copy -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"f_copy\">\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"f_logo\"><img src=\"./img/f_logo.gif\" alt=\"기프트마니\" /><br><br><br></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"f_cp\">공정거래위원회 고시 제 2000-1호에 따른 사업자등록번호 111-11-11111 / 통신판매업허가 관악 제 11-11111호<br>\r\n");
      out.write("\r\n");
      out.write("상호명 : PShoppingMall / 대표자명 : 김선중 / 개인정보 관리 책임자 : 변재정<br>\r\n");
      out.write("\r\n");
      out.write("TEL 02-111-1111(代) / FAX 02-111-1111 <br>\r\n");
      out.write("\r\n");
      out.write("회원 : 이재우 / 김진원 / 김종현 / 황희만<br>\r\n");
      out.write("\r\n");
      out.write("Copyright (C)1995~2006 ㈜앳디드 All Rights Reserved.\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--// footer copy -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--/ -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
