/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-07-30 07:16:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table style=\"width:100%; border: 1px solid black\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\r\n");
      out.write("<div id=\"head\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("<!-- TOP GNB -->\r\n");
      out.write("<!-- http://renewal.itcenter.co.kr/upload/logo/logo_28_2.gif -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"tgnb\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t<li><span class=\"log\"><a href=\"user_login.tiles\" id=\"topLogin\">로그인</a></span></li>\r\n");
      out.write("\t<li><span class=\"mem\"><a href=\"user_reg.tiles\" id=\"topMember\">회원가입</a></span></li>\r\n");
      out.write("\t<li><span class=\"cart\">|<a href=\"./order_cart.tiles\" id=\"topCart\">장바구니</a></span></li>\r\n");
      out.write("\t<li><span class=\"center\">|<a href=\"#\" id=\"board\">고객센터</a></span></li>\r\n");
      out.write("\t<li><span class=\"upload\"><a href=\"#\">이미지업로드</a></span></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- //TOP GNB -->\r\n");
      out.write("<!-- SEARCH --> \r\n");
      out.write("<div class=\"sta\">\r\n");
      out.write("<h1><a href=\"../main/main.asp\"><img src=\"./img/f_logo.gif\" width=\"146\" height=\"40\" ></a>\r\n");
      out.write("</h1>\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("<fieldset>\r\n");
      out.write("<legend>검색</legend>\r\n");
      out.write("<div class=\"search_box\">\r\n");
      out.write("<input type=\"text\" name=\"keyword\" title=\"검색\" value=\"\" accesskey=\"s\" class=\"search_text\">\r\n");
      out.write("<input src=\"./img/btn_srch.gif\" alt=\"검색\" type=\"image\" class=\"btn_search\">\r\n");
      out.write("</div>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("<h2><img src=\"./img/gnb_tel.gif\" alt=\"\"></h2>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //SEARCH -->\r\n");
      out.write("\r\n");
      out.write("<!-- MENU -->\r\n");
      out.write("<!-- GNB -->\r\n");
      out.write("<div id=\"gnb\">\r\n");
      out.write("<div class=\"gnb\">\r\n");
      out.write("<ul>\r\n");
      out.write("\r\n");
      out.write("<li id=\"topMenu1\"><a href=\"./goods_list.tiles\" class=\"menu_01\"><span>상품목록</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li id=\"topMenu2\"><a href=\"./order.tiles\" class=\"menu_01\"><span>주문하기</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li id=\"topMenu3\"><a href=\"./mypage_modify.tiles\" class=\"menu_01\"><span>마이페이지</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li id=\"topMenu4\"><a href=\"../product/sub.asp?categoryA=4\" class=\"menu_01\"><span>남성 스포츠 의류</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li id=\"topMenu5\"><a href=\"../product/sub.asp?categoryA=3\" class=\"menu_01\"><span>여성 스포츠 의류</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li id=\"topMenu6\"><a href=\"../product/sub.asp?categoryA=6\" class=\"menu_01\"><span>남성 캐쥬얼</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li id=\"topMenu7\"><a href=\"../product/sub.asp?categoryA=7\" class=\"menu_01\"><span>여성 캐쥬얼</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li id=\"topMenu8\"><a href=\"../product/sub.asp?categoryA=202\" class=\"menu_01\"><span>남성&amp;여성 모자</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //GNB -->\r\n");
      out.write("<!-- //MENU -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
