/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-07-30 08:18:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goods_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"width:39%; float:left\">\r\n");
      out.write("\t\t<table style=\"align:center; width:100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t이미지\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>thumb1</td>\r\n");
      out.write("\t\t\t\t<td>thumb2</td>\r\n");
      out.write("\t\t\t\t<td>thumb3</td>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"width:59%; float:left\">\r\n");
      out.write("\t\t<table style=\"align:center; width:100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_left\" width=\"40%\">\r\n");
      out.write("\t\t\t\t\t<label>상품명:</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_center1\">\r\n");
      out.write("\t\t\t\t\t<label></label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_left\">\r\n");
      out.write("\t\t\t\t\t<label>상품코드:</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_center1\">\r\n");
      out.write("\t\t\t\t\t<label></label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_left\">\r\n");
      out.write("\t\t\t\t\t<label>가격:</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_center1\">\r\n");
      out.write("\t\t\t\t\t<label></label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_left\">\r\n");
      out.write("\t\t\t\t\t<label>옵션:</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_center1\">\r\n");
      out.write("\t\t\t\t\t<label></label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_left\">\r\n");
      out.write("\t\t\t\t\t<label>제조사/원산지:</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_center1\">\r\n");
      out.write("\t\t\t\t\t<label></label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_left\">\r\n");
      out.write("\t\t\t\t\t<label>수량:</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_center1\">\r\n");
      out.write("\t\t\t\t\t<label></label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_left\">\r\n");
      out.write("\t\t\t\t\t<label>총 금액:</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_center1\">\r\n");
      out.write("\t\t\t\t\t<label></label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_center1\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<label class=\"jw_lbl_title\">총 구매 금액이 Xx이상시 배송비무료</label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"jw_td_center1\" colspan=\"2\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"장바구니\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"바로구매\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"찜하기\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"width:99%; padding-left: 10px\">\r\n");
      out.write("\t\t<label class=\"jw_lbl_title\">상품 정보 및 설명</label> <br/>\r\n");
      out.write("\t\t<label >!@#$%!@$%@#$%@#$%!@$%!@$%!@#$%#</label>\r\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
