/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-07-30 09:26:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sitehelper;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sitehelper_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>ADMIN LOGIN PAGE</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../common/jquery-1.7.2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#loginBtn\").bind(\"click\", function() {\r\n");
      out.write("\t\t\tif ($(\"#adminId\").val() == '') {\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#adminId\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($(\"#adminPwd\").val() == '') {\r\n");
      out.write("\t\t\t\talert(\"패스워드를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#adminPwd\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.post(\"loginchk.do\", $(\"form\").serialize(), function(data){\r\n");
      out.write("\t\t\t\talert(\"ajax get return\");\r\n");
      out.write("\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\tif (data == 'ok') {\r\n");
      out.write("\t\t\t\t\tlocation.href = '/index.jsp';\r\n");
      out.write("\t\t\t\t} else if (data == 'id' || data == 'pw') {\r\n");
      out.write("\t\t\t\t\talert('아이디 비번을 확인하세요.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if (data == 'notShop') {\r\n");
      out.write("\t\t\t\t\talert('등록되지 않은 가맹점입니다.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(data + '에러가 발생하였습니다.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#loginBtn2\").bind(\"click\", function() {\r\n");
      out.write("            if ($(\"#adminId2\").val() == '') {\r\n");
      out.write("                alert(\"아이디를 입력하세요\");\r\n");
      out.write("                $(\"#adminId2\").focus();\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#adminPwd2\").val() == '') {\r\n");
      out.write("                alert(\"패스워드를 입력하세요\");\r\n");
      out.write("                $(\"#adminPwd2\").focus();\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            $.post(\"loginchk2.do\", $(\"form\").serialize(), function(data){\r\n");
      out.write("                alert(data+\"2\");\r\n");
      out.write("                if (data == 'ok') {\r\n");
      out.write("                    location.href = '/index.jsp';\r\n");
      out.write("                } else if (data == 'id' || data == 'pw') {\r\n");
      out.write("                    alert('아이디 비번을 확인하세요.');\r\n");
      out.write("                    return false;\r\n");
      out.write("                } else if (data == 'notShop') {\r\n");
      out.write("                    alert('등록되지 않은 가맹점입니다.');\r\n");
      out.write("                    return false;\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(data + '에러가 발생하였습니다.');\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>관리자 로그인</h2>\r\n");
      out.write("\r\n");
      out.write("\t<form method=\"post\">\r\n");
      out.write("\tID :<input type=\"text\" name=\"adminId\" id=\"adminId\" value=\"admin\" /><br />\r\n");
      out.write("\tPW :<input type=\"password\" name=\"adminPwd\" id=\"adminPwd\" value=\"test\" /><br />\r\n");
      out.write("\t<button id=\"loginBtn\">로그인</button>\r\n");
      out.write("\t<hr />\r\n");
      out.write("    ID :<input type=\"text\" name=\"adminId2\" id=\"adminId2\" value=\"admin\" /><br />\r\n");
      out.write("    PW :<input type=\"password\" name=\"adminPwd2\" id=\"adminPwd2\" value=\"test\" /><br />\r\n");
      out.write("    <button id=\"loginBtn2\">컨넥션풀로그인</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
