/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-07-30 07:36:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005ffind_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".tab{\r\n");
      out.write("\tborder:1px solid black; \r\n");
      out.write("\tpadding:10px; \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"sub_loca\"><img src=\"./img/icon_home.gif\" alt=\"현재위치\" />홈 > 아이디/비밀번호 찾기</div>\r\n");
      out.write("\r\n");
      out.write("\t<table bgcolor=\"0066FF\" align=\"center\" width=\"50%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td> 이름 </td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td> 이메일 </td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"email\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\"> <input type=\"button\" value=\"아이디찾기\">\r\n");
      out.write("\t\t\t\t <input type=\"button\" value=\"비밀번호찾기\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t            <div class=\"pop01_scon\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"pop01_sscon\">\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"pop01_txt\"><img src=\"../images/member/dot_arrow.gif\" alt=\"\" />회원가입시 작성한 이름과 전화번호, 이메일주소를 <span class=\"pop01_indent\">입력해주시기 바랍니다.</span></span>\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"pop01_txt\"><img src=\"../images/member/dot_arrow.gif\" alt=\"\" />전화번호는 (-) 없이 띄지말고 입력하세요.</span>\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"pop01_txt\"><img src=\"../images/member/dot_arrow.gif\" alt=\"\" />아이디/비밀번호는 입력하신 이메일로 발송됩니다.</span>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
