/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-07-30 07:36:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005freg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"sub_loca\"><img src=\"./img/icon_home.gif\" alt=\"현재위치\" />홈 > 회원가입</div>\r\n");
      out.write("<form action=\"user_success.jsp\">\r\n");
      out.write("\t<div class=\"join01_tt\">\r\n");
      out.write("\r\n");
      out.write("\t\t<span class=\"join01_tt01\"><img src=\"./img/join01_timg.gif\" alt=\"정보입력\" /></span>\r\n");
      out.write("\r\n");
      out.write("\t\t<span class=\"join01_tt02\"><img src=\"./img/join01_txt.gif\" alt=\"회원가입은 무료이며,회원약관을 꼭 읽고 숙지하시기 바랍니다.\" /></span>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"join02_form01\">\r\n");
      out.write("\t<table class=\"join02_form02\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td> \r\n");
      out.write("\t\t\t\t<label class=\"lbl_title\">이용약관</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<textarea rows=\"10\" cols=\"100\" readonly>\r\n");
      out.write("PShoppingMall은 공정거래위원회가 승인한 표준약관을 사용합니다.\r\n");
      out.write("\r\n");
      out.write("제1조(목적)\r\n");
      out.write("이 약관은 PShoppingMall이 운영하는 \"판촉물\"에서 제공하는 인터넷 관련 서비스(이하 \"서비스\"라 한다)를 이용함에 있어 사이버몰과 이용자의 권리·의무 및 책임사항을 규정함을 목적으로 합니다.\r\n");
      out.write("\r\n");
      out.write("제2조(정의)\r\n");
      out.write("① \"판촉물\" 이란 판촉물(이)가 재화 또는 용역을 이용자에게 제공하기 위하여 컴퓨터등 정보통신설비를 이용하여 재화 또는 용역을 거래할 수 있도록 설정한 가상의 영업장을 말하며, 아울러 사이버몰을 운영하는 사업자의 의미로도 사용합니다.\r\n");
      out.write("② \"이용자\"란 \"판촉물\"에 접속하여 이 약관에 따라 \"판촉물\"(이)가 제공하는 서비스를 받는 회원 및 비회원을 말합니다. \r\n");
      out.write("③ 회원''이라 함은 \"판촉물\"에 개인정보를 제공하여 회원등록을 한 자로서, \"판촉물\"의 정보를 지속적으로 제공받으며, \"판촉물\"(이)가 제공하는 서비스를 계속적으로 이용할 수 있는 자를 말합니다. \r\n");
      out.write("④ 비회원''이라 함은 회원에 가입하지 않고 \"판촉물\"(이)가 제공하는 서비스를 이용하는 자를 말합니다. \r\n");
      out.write("\r\n");
      out.write("제3조 (약관의 명시와 개정)\r\n");
      out.write("① \"판촉물\"은 이 약관의 내용과 상호, 영업소 소재지, 대표자의 성명, 사업자등록번호, 연락처(전화, 팩스, 전자우편 주소 등) 등을 이용자가 알 수 있도록 \"PShoppingMall\"의 초기 서비스화면(전면)에 게시합니다.\r\n");
      out.write("② \"판촉물\"은 약관의규제등에관한법률, 전자거래기본법, 전자서명법, 정보통신망이용촉진등에관한법률, 방문판매등에관한법률, 소비자보호법 등 관련법을 위배하지 않는 범위에서 이 약관을 개정할 수 있습니다.\r\n");
      out.write("③ \"판촉물\"(이)가 약관을 개정할 경우에는 적용일자 및 개정사유를 명시하여 현행약관과 함께 몰의 초기화면에 그 적용일자 7일이전부터 적용일자 전일까지 공지합니다.\r\n");
      out.write("④ \"판촉물\"(이)가 약관을 개정할 경우에는 그 개정약관은 그 적용일자 이후에 체결되는 계약에만 적용되고 그 이전에 이미 체결된 계약에 대해서는 개정전의 약관조항이 그대로 적용됩니다. 다만 이미 계약을 체결한 이용자가 개정약관 조항의 적용을 받기를 원하는 뜻을 제3항에 의한 개정약관의 공지기간내에 ''몰\"에 송신하여 \"판촉물\"의 동의를 받은 경우에는 개정약관 조항이 적용됩니다.\r\n");
      out.write("⑤ 이 약관에서 정하지 아니한 사항과 이 약관의 해석에 관하여는 정부가 제정한 전자거래소비자보호지침 및 관계법령 또는 상관례에 따릅니다. \r\n");
      out.write("⑥ 회원은 변경된 약관이 공지된 후 15일 이내에 거부의사를 표명할 수 있습니다. 회원이 거부하는 경우 회사는 당해 회원과의 계약을 해지할 수 있습니다.\r\n");
      out.write("만약 회원이 변경된 약관이 공지된 후 15일 이내에 거부의사를 표시하지 않는 경우에는 동의하는 것으로 간주합니다. \r\n");
      out.write("⑦ 이 약관은 서비스를 통하여 이를 공지함으로써 효력이 발생됩니다. \r\n");
      out.write("⑧ 회사는 사정상 중요한 사유가 발생될 경우 사전 고지 없이 이 약관의 내용을 변경할 수 있으며, 변경된 약관은 서비스를 통하여 공지합니다. \r\n");
      out.write("\r\n");
      out.write("제4조(서비스의 제공 및 변경)\r\n");
      out.write("① \"판촉물\"은 다음과 같은 업무를 수행합니다.\r\n");
      out.write("1. 재화 또는 용역에 대한 정보 제공 및 구매계약의 체결\r\n");
      out.write("2. 구매계약이 체결된 재화 또는 용역의 배송\r\n");
      out.write("3. 기타 \"판촉물\"(이)가 정하는 업무\r\n");
      out.write("② \"판촉물\"은 재화의 품절 또는 기술적 사양의 변경 등의 경우에는 장차 체결되는 계약에 의해 제공할 재화·용역의 내용을 변경할 수 있습니다. 이 경우에는 변경된 재화·용역의 내용 및 제공일자를 명시하여 현재의 재화·용역의 내용을 게시한 곳에 그 제공일자 이전 7일부터 공지합니다.\r\n");
      out.write("단, 정확한 변동가격 및 품절시점 등 변동내용을 구체적으로 공지하기가 불가능한 경우에는 7일전에 그 취지 및 공지가 불가능한 변동사유를 현재의 재화.용역을 게시한 곳에 공지합니다.\r\n");
      out.write("③ \"판촉물\"(이)가 제공하기로 이용자와 계약을 체결한 서비스의 내용을 재화의 품절 또는 기술적 사양의 변경등의 사유로 변경할 경우에는 \"판촉물\"은 이로 인하여 이용자가 입은 손해를 배상합니다. 단, \"판촉물\"에 고의 또는 과실이 없는 경우에는 그러하지 아니합니다. \r\n");
      out.write("\r\n");
      out.write("제5조(서비스의 중단)\r\n");
      out.write("① \"판촉물\"은 컴퓨터 등 정보통신설비의 보수점검·교체 및 고장, 통신의 두절 등의 사유가 발생한 경우에는 서비스의 제공을 일시적으로 중단할 수 있습니다.\r\n");
      out.write("② 제1항에 의한 서비스 중단의 경우에는 \"판촉물\"은 제8조에 정한 방법으로 이용자에게 통지합니다. \r\n");
      out.write("③ \"판촉물\"은 제1항의 사유로 서비스의 제공이 일시적으로 중단됨으로 인하여 이용자 또는 제3자가 입은 손해에 대하여 배상합니다. 단 \"판촉물\"에 고의 또는 과실이 없는 경우에는 그러하지 아니합니다.\r\n");
      out.write("\r\n");
      out.write("제6조(회원가입)\r\n");
      out.write("① 이용자는 \"판촉물\"(이)가 정한 가입 양식에 따라 회원정보를 기입한 후 이 약관에 동의한다는 의사표시를 함으로서 회원가입을 신청합니다. (단, 만 14세 미만의 어린이의 회원가입시 법정대리인의 허락을 받아야 하며, 만 14세 미만의 어린이에게는 광고성 메일을 발송하지 않습니다.)\r\n");
      out.write("② \"판촉물\"은 제1항과 같이 회원으로 가입할 것을 신청한 이용자 중 다음 각호에 해당하지 않는 한 회원으로 등록합니다. \r\n");
      out.write("1. 가입신청자가 이 약관 제7조제3항에 의하여 이전에 회원자격을 상실한 적이 있는 경우, 다만 제7조제3항에 의한 회원자격 상실후 3년이 경과한 자로서 \"판촉물\"의 회원재가입 승낙을 얻은 경우에는 예외로 한다.\r\n");
      out.write("2. 등록 내용에 허위, 기재누락, 오기가 있는 경우 \r\n");
      out.write("3. 기타 회원으로 등록하는 것이 \"판촉물\"의 기술상 현저히 지장이 있다고 판단되는 경우 \r\n");
      out.write("4. 만 14세 미만인 자\r\n");
      out.write("③ 회원가입계약의 성립시기는 \"판촉물\"의 승낙이 회원에게 도달한 시점으로 합니다. \r\n");
      out.write("④ 회원은 제15조제1항에 의한 등록사항에 변경이 있는 경우, 즉시 전자우편 기타 방법으로 \"판촉물\"에 대하여 그 변경사항을 알려야 합니다.\r\n");
      out.write("\r\n");
      out.write("제7조(회원 탈퇴 및 자격 상실 등)\r\n");
      out.write("① 회원은 \"판촉물\"에 언제든지 탈퇴를 요청할 수 있으며 \"판촉물\"은 즉시 회원탈퇴를 처리합니다.\r\n");
      out.write("② 회원이 다음 각호의 사유에 해당하는 경우, \"판촉물\"은 회원자격을 제한 및 정지시킬 수 있습니다. \r\n");
      out.write("1. 가입 신청시에 허위 내용을 등록한 경우 \r\n");
      out.write("2. \"판촉물\"을 이용하여 구입한 재화·용역 등의 대금, 기타 \"판촉물\"이용에 관련하여 회원이 부담하는 채무를 기일에 지급하지 않는 경우 \r\n");
      out.write("3. 다른 사람의 \"판촉물\" 이용을 방해하거나 그 정보를 도용하는 등 전자거래질서를 위협하는 경우 \r\n");
      out.write("4. \"판촉물\"을 이용하여 법령과 이 약관이 금지하거나 공서양속에 반하는 행위를 하는 경우\r\n");
      out.write("③ \"판촉물\"(이)가 회원 자격을 제한·정지 시킨후, 동일한 행위가 2회이상 반복되거나 30일이내에 그 사유가 시정되지 아니하는 경우 \"판촉물\"은 회원자격을 상실시킬 수 있습니다.\r\n");
      out.write("④ \"판촉물\"이 회원자격을 상실시키는 경우에는 회원등록을 말소합니다. 이 경우 회원에게 이를 통지하고, 회원등록 말소전에 소명할 기회를 부여합니다. \r\n");
      out.write("\r\n");
      out.write("제8조(회원에 대한 통지)\r\n");
      out.write("① \"판촉물\"(이)가 회원에 대한 통지를 하는 경우, 회원이 \"판촉물\"에 제출한 전자우편 및 모바일주소로 할 수 있습니다.\r\n");
      out.write("② \"판촉물\"은 불특정다수 회원에 대한 통지의 경우 1주일이상 \"판촉물\" 게시판에 게시함으로서 개별 통지에 갈음할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제9조(구매신청)\r\n");
      out.write("\"판촉물\"이용자는 \"판촉물\"상에서 이하의 방법에 의하여 구매를 신청합니다.\r\n");
      out.write("1. 성명, 주소, 전화번호 입력\r\n");
      out.write("2. 재화 또는 용역의 선택\r\n");
      out.write("3. 결제방법의 선택 \r\n");
      out.write("4. 이 약관에 동의한다는 표시(예, 마우스 클릭)\r\n");
      out.write("\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<div style=\"width:60%; text-align:right\">\r\n");
      out.write("\t\t<input type=\"checkbox\">\r\n");
      out.write("\t\t<label>동의합니다</label>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<div class=\"sub_v_tt\">\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>회원가입</h2>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"join01_tt\">\r\n");
      out.write("\r\n");
      out.write("\t\t<span class=\"join01_tt01\"><img src=\"./img/join02_timg.gif\" alt=\"정보입력\" /></span>\r\n");
      out.write("\r\n");
      out.write("\t\t<span class=\"join01_tt02\"><img src=\"./img/join01_txt.gif\" alt=\"회원가입은 무료이며,회원약관을 꼭 읽고 숙지하시기 바랍니다.\" /></span>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"join02_sctt\">\r\n");
      out.write("\t\t<span class=\"join02_stt01\"><img src=\"./img/join02_stt01.gif\" alt=\"개인정보입력\" /></span>\r\n");
      out.write("\t\t<span class=\"join02_stt02\"><b>*</b> 는 필수 정보입력 항목입니다.</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"join02_form01\">\r\n");
      out.write("\t<table class=\"join02_form02\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" class=\"sub_v_tt\">\r\n");
      out.write("\t\t\t\t<label class=\"lbl_title\">회원정보</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr class=\"join02_tr\">\r\n");
      out.write("\t\t\t<td style=\"width:40%\" class=\"join02_left01\">\r\n");
      out.write("\t\t\t\t<label><b>*</b>이름</label></td>\r\n");
      out.write("\t\t\t<td class=\"join02_right\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"text\" name=\"name\"> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr class=\"join02_tr\">\r\n");
      out.write("\t\t\t<td class=\"join02_left01\"> \r\n");
      out.write("\t\t\t\t<label><b>*</b>아이디</label></td>\r\n");
      out.write("\t\t\t<td class=\"join02_right\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"text\" name=\"id\"> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr class=\"join02_tr\">\r\n");
      out.write("\t\t\t<td class=\"join02_left01\">\r\n");
      out.write("\t\t\t\t<label><b>*</b>비밀번호</label></td>\r\n");
      out.write("\t\t\t<td class=\"join02_right\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"password\" name=\"pw\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr class=\"join02_tr\">\r\n");
      out.write("\t\t\t<td class=\"join02_left01\">\r\n");
      out.write("\t\t\t\t<label><b>*</b>비밀번호확인</label></td>\r\n");
      out.write("\t\t\t<td class=\"join02_right\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"password\" name=\"rpw\"> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr class=\"join02_tr\">\r\n");
      out.write("\t\t\t<td class=\"join02_left01\">\r\n");
      out.write("\t\t\t\t<label><b>*</b>전화번호</label></td>\r\n");
      out.write("\t\t\t<td class=\"join02_right\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"text\" name=\"tel\"> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr class=\"join02_tr\">\r\n");
      out.write("\t\t\t<td class=\"join02_left01\">\r\n");
      out.write("\t\t\t\t<label>휴대폰</label></td>\r\n");
      out.write("\t\t\t<td class=\"join02_right\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"text\" name=\"cell\"> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr class=\"join02_tr\">\r\n");
      out.write("\t\t\t<td class=\"join02_left01\">\r\n");
      out.write("\t\t\t\t<label><b>*</b>우편번호</label></td>\r\n");
      out.write("\t\t\t<td class=\"join02_right\"> <input type=\"text\" name=\"zipcode\" size=\"7\"> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr class=\"join02_tr\">\r\n");
      out.write("\t\t\t<td class=\"join02_left01\">\r\n");
      out.write("\t\t\t\t<label><b>*</b>주소</label></td>\r\n");
      out.write("\t\t\t<td class=\"join02_right\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"text\" name=\"addr\"> <br/> \r\n");
      out.write("\t\t\t\t<INPUT type=\"text\" name=\"detailaddr\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr class=\"join02_tr\">\r\n");
      out.write("\t\t\t<td class=\"join02_left01\">\r\n");
      out.write("\t\t\t\t<label><b>*</b>이메일</label></td>\r\n");
      out.write("\t\t\t<td class=\"join02_right\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"text\" name=\"email\" size=\"25\"> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"right\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"가입\">\r\n");
      out.write("\t\t\t\t<input type=\"reset\" value=\"취소\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
