/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-07-30 09:30:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"sub_loca\">\r\n");
      out.write("\t\t<img src=\"./img/icon_home.gif\" alt=\"현재위치\" />홈 > 주문하기\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"jw_normal_table\" style=\"width:100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=5>\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">주문자 정보</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">이름</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">전화번호</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">휴대전화</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">주소</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">이메일</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>이름</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>전화번호</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>휴대전화</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>주소</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>이메일</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"text-align:right\">\r\n");
      out.write("\t\t<input type=\"checkbox\" value=\"same\">주문정보 동일\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"jw_normal_table\" style=\"width:100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=5>\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">배송 정보</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">이름</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">전화번호</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">휴대전화</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">주소</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_theader\">\r\n");
      out.write("\t\t\t\t<label class=\"jw_lbl_title\">이메일</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>이름</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>전화번호</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>휴대전화</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>주소</label></td>\r\n");
      out.write("\t\t\t<td class=\"jw_td_center\">\r\n");
      out.write("\t\t\t\t<label>이메일</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"jw_div_center\">\r\n");
      out.write("\t\t<label>무통장 입금</label>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"jw_div_right\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"결제\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"취소\">\r\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
